export const Captions = [
  "Speakers & Participants of Civic Engagement 4.0 Forum",
  "Day 1: Thematic Sites Visit - Batik Making Process in Kampung Batik Laweyan",
  "Day 1: Thematic Sites Visit - Batik Making Process in Kampung Batik Laweyan",
  "Day 1: Thematic Sites Visit - Keraton Kasunanan Surakarta",
  "Day 1: Thematic Sites Visit",
  "Day 1: Thematic Sites Visit - Pasar Gede",
  "Day 1: Thematic Sites Visit - Pasar Gede",
  "Day 1: Thematic Sites Visit",
  "Day 2: Public Forum - Panel Discussion",
  "Day 2: Public Forum - Group Discussion",
  "Day 2: Public Forum - Panel Discussion",
  "Day 2: Public Forum - Panel Discussion",
  "Day 2: Public Forum - Panel Discussion",
  "Day 2: Public Forum - Panel Discussion",
  "Day 2: Public Forum - Panel Discussion",
  "Day 3: Mayors’ Symposium - Opening Plenary",
  "Day 3: Mayors’ Symposium - Mayors’ Innovation Pitch",
  "Day 3: Mayors’ Symposium - Q & A Session",
  "Day 3: Mayors’ Symposium - Mayors’ Interface with Civil Society",
  "Participants of Civic Engagement 4.0",
  "Volunteers of Civic Engagement 4.0",
]
